Repository uberduck-ai/openduck, pull requests merged in 2024-04, with the labels that each got.

#116 prompt changes and noise cancellation
  openduck-py/openduck_py/prompts/comedy.txt
  openduck-py/openduck_py/response_agent.py
  openduck-py/openduck_py/routers/voice.py
  openduck-py/openduck_py/settings.py
  web/src/app/page.tsx
Labels: enhancement, bug_fix

#117 speech prob and settings refactor
  openduck-py/openduck_py/routers/ml.py
  openduck-py/openduck_py/settings.py
Labels: enhancement, bug_fix

#118 Change no_speech_prob threshold to 0.5
  openduck-py/openduck_py/settings.py
Labels: enhancement

#120 Return empty string if whisper returns no segments
  openduck-py/openduck_py/prompts/comedy.txt
  openduck-py/openduck_py/routers/ml.py
Labels: enhancement, bug_fix

#119 Show recording after call ends
  openduck-py/openduck_py/models/chat_history.py
  openduck-py/openduck_py/routers/voice.py
  openduck-py/openduck_py/settings.py
  openduck-py/openduck_py/utils/daily.py
  web/src/app/page.tsx
Labels: enhancement, bug_fix

#123 Migration file
  openduck-py/openduck_py/alembic/versions/4a8aae996f95_add_recording_url.py
Labels: enhancement

#124 Interruptions changes
  openduck-py/openduck_py/response_agent.py
Labels: enhancement, bug_fix

#121 Check all whisper response["segments"] for no_speech_prob < 0.5
  openduck-py/openduck_py/routers/ml.py
Labels: enhancement, bug_fix

#125 Personas config and tts options
  openduck-py/openduck_py/response_agent.py
  openduck-py/openduck_py/routers/voice.py
Labels: enhancement, configuration changes

#127 fix interrupts
  openduck-py/openduck_py/response_agent.py
Labels: enhancement, bug_fix

#129 Set LOG_TO_S3 = True
  openduck-py/openduck_py/settings.py
Labels: enhancement
