Repository uberduck-ai/openduck, pull requests merged in 2024-03, with the labels that each got.

#47 Delete some dependencies
  openduck-py/requirements.txt
Labels: enhancement

#52 fix paths
  openduck-py/openduck_py/voices/styletts2.py
Labels: bug_fix

#54 Use daily on the server
  docker-compose.yml
  openduck-py/openduck_py/routers/voice.py
  openduck-py/requirements.txt
Labels: enhancement

#55 Daily client
  clients/daily/daily_bot.py
Labels: enhancement

#56 bug fix: Don't send the audio_chunk if it is None
  openduck-py/openduck_py/routers/voice.py
Labels: bug_fix

#57 stop daily bot on ctrl c
  clients/daily/daily_bot.py
Labels: bug_fix

#63 adding migration file I forgot
  openduck-py/observability.py
  openduck-py/openduck_py/alembic/versions/6bbc3879a288_latency_seconds.py
  openduck-py/openduck_py/models/chat_record.py
  openduck-py/openduck_py/routers/voice.py
Labels: enhancement

#65 Streaming LLM output
  openduck-py/openduck_py/routers/voice.py
Labels: enhancement

#68 dedicated db path for volume mounting
  .gitignore
  openduck-py/openduck_py/db/__init__.py
Labels: enhancement

#70 remove segment audio
  openduck-py/openduck_py/routers/voice.py
Labels: enhancement

#73 add an ML_API_URL env variable
  .env.example
  openduck-py/openduck_py/routers/main.py
  openduck-py/openduck_py/routers/ml.py
  openduck-py/openduck_py/routers/voice.py
  openduck-py/openduck_py/settings/__init__.py
Labels: enhancement, configuration changes

#75 fix cors
  openduck-py/openduck_py/routers/main.py
Labels: bug_fix

#76 improvements
  openduck-py/openduck_py/routers/voice.py
  web/src/app/page.tsx
Labels: enhancement, bug_fix

#77 Move the normalizer to the ML API
  docker-compose.yml
  openduck-py/openduck_py/routers/ml.py
  openduck-py/openduck_py/routers/voice.py
  openduck-py/openduck_py/settings/__init__.py
Labels: enhancement, bug_fix

#79 lazy load torch
  openduck-py/openduck_py/routers/voice.py
Labels: enhancement

#80 [wip] improvements
  openduck-py/openduck_py/prompts/most-interesting-bot/system-prompt.md
  openduck-py/openduck_py/routers/main.py
  openduck-py/openduck_py/routers/voice.py
  openduck-py/openduck_py/settings/__init__.py
  web/src/app/page.tsx
Labels: enhancement, configuration changes

#82 Podcast with 2 bots
  openduck-py/openduck_py/configs/tts_config.py
  openduck-py/openduck_py/prompts/most-interesting-bot/podcast_guest.md
  openduck-py/openduck_py/prompts/most-interesting-bot/podcast_host.md
  openduck-py/openduck_py/routers/voice.py
  openduck-py/openduck_py/utils/third_party_tts.py
  web/package-lock.json
  web/package.json
Labels: enhancement, bug_fix

#85 refactor, better assistant
  openduck-py/openduck_py/__init__.py
  openduck-py/openduck_py/logging/db.py
  openduck-py/openduck_py/response_agent.py
  openduck-py/openduck_py/routers/voice.py
  openduck-py/openduck_py/settings/__init__.py
  openduck-py/openduck_py/utils/daily.py
  web/src/app/page.tsx
Labels: enhancement, bug_fix

#95 Upload logged audio files to S3
  .env.example
  openduck-py/openduck_py/logging/db.py
  openduck-py/openduck_py/response_agent.py
  openduck-py/openduck_py/routers/voice.py
  openduck-py/openduck_py/settings/__init__.py
Labels: enhancement, bug_fix

#97 Matthew deepgram
  .env.example
  openduck-py/openduck_py/response_agent.py
  openduck-py/openduck_py/settings.py
  openduck-py/openduck_py/utils/daily.py
Labels: enhancement

#98 Improve interruption handling
  openduck-py/openduck_py/logging/db.py
  openduck-py/openduck_py/logging/slack.py
  openduck-py/openduck_py/models/chat_record.py
  openduck-py/openduck_py/prompts/__init__.py
  openduck-py/openduck_py/prompts/intros/greeting.txt
  openduck-py/openduck_py/response_agent.py
  openduck-py/openduck_py/routers/main.py
  openduck-py/openduck_py/routers/voice.py
  openduck-py/openduck_py/utils/daily.py
  openduck-py/openduck_py/utils/third_party_tts.py
  openduck-py/requirements.txt
  web/src/app/page.tsx
Labels: enhancement, bug_fix

#101 Deepgram streaming
  openduck-py/openduck_py/response_agent.py
Labels: enhancement, bug_fix

#104 Remove daily service from docker-compose, and remove ml_router from the web service
  .env.example
  docker-compose.yml
Labels: enhancement, configuration changes

#105 zach prompt engineering
  openduck-py/openduck_py/logging/slack.py
  openduck-py/openduck_py/prompts/intros/greeting.txt
  openduck-py/openduck_py/prompts/most-interesting-bot/intro-prompt.md
  openduck-py/openduck_py/prompts/most-interesting-bot/podcast_guest.md
  openduck-py/openduck_py/prompts/most-interesting-bot/podcast_host.md
  openduck-py/openduck_py/response_agent.py
  openduck-py/openduck_py/routers/voice.py
  openduck-py/openduck_py/utils/daily.py
  web/src/app/page.tsx
Labels: enhancement, bug_fix

#106 Measure LLM and TTS latencies more accurately
  openduck-py/openduck_py/logging/db.py
  openduck-py/openduck_py/response_agent.py
  openduck-py/openduck_py/routers/voice.py
Labels: enhancement

#107 delete unused imports
  openduck-py/openduck_py/models/chat_history.py
  openduck-py/openduck_py/models/chat_record.py
  openduck-py/openduck_py/routers/rooms.py
  openduck-py/openduck_py/routers/voice.py
Labels: enhancement

#108 azure tts
  .env.example
  openduck-py/openduck_py/configs/tts_config.py
  openduck-py/openduck_py/logging/slack.py
  openduck-py/openduck_py/prompts/most-interesting-bot/podcast_host.md
  openduck-py/openduck_py/response_agent.py
  openduck-py/openduck_py/routers/voice.py
  openduck-py/openduck_py/utils/third_party_tts.py
  openduck-py/requirements.txt
Labels: documentation, enhancement

#109 Dockerfile OpenSSL fix
  Dockerfile
Labels: enhancement

#110 increase number of attempts for daily recording
  openduck-py/openduck_py/settings.py
  openduck-py/openduck_py/utils/daily.py
Labels: enhancement, bug_fix

#111 use openai tts
  openduck-py/openduck_py/routers/voice.py
Labels: enhancement

#112 changes
  openduck-py/openduck_py/prompts/most-interesting-bot/podcast_host.md
  openduck-py/openduck_py/response_agent.py
  openduck-py/openduck_py/routers/ml.py
  openduck-py/openduck_py/routers/voice.py
  openduck-py/openduck_py/settings.py
Labels: enhancement, bug_fix

#113 GPT-SoVITS
  .env.example
  clients/daily/daily_bot.py
  docker-compose.yml
  openduck-py/openduck_py/configs/tts_config.py
  openduck-py/openduck_py/logging/slack.py
  openduck-py/openduck_py/response_agent.py
  openduck-py/openduck_py/routers/voice.py
  openduck-py/openduck_py/utils/third_party_tts.py
Labels: enhancement
